AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2. Kittens Carousel Static Website will be deployed on Amazon Linux 2023 EC2 Instance with custom security group which allows http connections on port 80 and ssh port 22 from anywhere. Kittens Carousel Static Website
  is downloaded from my Public Github repository, then deployed on Apache Web Server.

Parameters:
  imageId: 
   Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
   Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
  keyPair:
    Description: Choose your keypair 
    Type: AWS::EC2::KeyPair::KeyName
    Default: firstkey

  instanceType:
    Description: Choose your instance type 
    Type: String 
    Default: t2.micro 
    AllowedValues:
      - t2.micro
      - t3.micro
      - t2.large


Resources:
  eda:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref imageId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPair
      UserData: !Base64 |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          yum install -y wget
          cd /var/www/html
          wget https://raw.githubusercontent.com/EdanurGega/project3/main/static-web/index.html
          wget https://raw.githubusercontent.com/EdanurGega/project3/main/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/EdanurGega/project3/main/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/EdanurGega/project3/main/static-web/cat2.jpg

      SecurityGroupIds:
        - !Ref newSec #GetAtt newSec.GroupId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  newSec:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow incoming traffic on port 22,80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  

Outputs:
  webSiteURL:
    Description: URL of website
    Value: !Sub
      - http://${PublicDNS}
      - PublicDNS: !GetAtt eda.PublicDnsName
